sonar.projectName=LMS Frontend
sonar.organization=ashwin101103
sonar.projectKey=Ashwin101103_lms-frontend
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/tests/**,**/coverage/**,**/public/**
sonar.test.inclusions=**/*.test.js,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
